from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import sys
import pyautogui
from PIL import ImageGrab
import time
import Graph_Class


class Ui_MainWindow(object):


    def __init__(self): 
        # Be careful there is a difference between Graph_1 and Graph_One. The first one is an object of the class we created, but the second one is the name
        # of the plot widget of the Top Graph.
        self.Graph_1 = Graph_Class.Graph(1, self, None, None)
        self.Graph_2 = Graph_Class.Graph(2, self, None, None)
        # Every graph has to be able to access the other one as they can be Linked
        self.Graph_1.Other_Graph = self.Graph_2
        self.Graph_2.Other_Graph = self.Graph_1
        self.Top_Scrolling_Coordinates_value = None
        self.Bottom_Scrolling_Coordinates_value = None
        self.Snapshots_Count = 0
        self.Snapshots_Taken = [] # This List stores each snapshot was taken from which graph, 1 or 2


    def Take_Snapshot(self):
        self.Export_Button.setEnabled(True)
        #Shortcut to take screenshot
        pyautogui.hotkey("win", "shift", "s")
        #wait till user takes screenshot
        time.sleep(4)
        snapshot = ImageGrab.grabclipboard()
        selected_graph = self.Snapshot_Combobox.currentText()
        if selected_graph == "Graph 1":
            self.Snapshots_Taken.append(1)
        else:
            self.Snapshots_Taken.append(2)
        # Save the image to Snapshots folder
        snapshot.save(f'Snapshots/image{self.Snapshots_Count}.png', 'PNG')
        self.Snapshots_Count += 1
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1689, 871)
        MainWindow.setMinimumSize(QtCore.QSize(1201, 801))
        MainWindow.setStyleSheet("background-color: #1e1e2f;\n" "color:white;\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(641, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 251))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.Load1_Button = QtWidgets.QPushButton(self.frame_4,clicked=lambda: self.Graph_1.Browse_Signals())
        self.Load1_Button.setStyleSheet("background-color:#3366ff;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/load1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Load1_Button.setIcon(icon)
        self.Load1_Button.setObjectName("Load1_Button")
        self.verticalLayout_2.addWidget(self.Load1_Button)
        self.Play1_Button = QtWidgets.QPushButton(self.frame_4, clicked = lambda : self.Graph_1.Toggle_Play_Pause())
        self.Play1_Button.setEnabled(False)
        self.Play1_Button.setStyleSheet("background-color:#3366ff;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/pause-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play1_Button.setIcon(icon1)
        self.Play1_Button.setObjectName("Play1_Button")
        self.verticalLayout_2.addWidget(self.Play1_Button)
        self.Rewind1_Button = QtWidgets.QPushButton(self.frame_4, clicked = lambda : self.Graph_1.Rewind_Signal())
        self.Rewind1_Button.setEnabled(False)
        self.Rewind1_Button.setStyleSheet("background-color:#3366ff;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rewind1_Button.setIcon(icon2)
        self.Rewind1_Button.setObjectName("Rewind1_Button")
        self.verticalLayout_2.addWidget(self.Rewind1_Button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ZoomOut1_Button = QtWidgets.QPushButton(self.frame_4, clicked = lambda: self.Graph_1.ZoomOut())
        self.ZoomOut1_Button.setMinimumSize(QtCore.QSize(71, 31))
        self.ZoomOut1_Button.setStyleSheet("background-color:#3366ff;")
        self.ZoomOut1_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZoomOut1_Button.setIcon(icon3)
        self.ZoomOut1_Button.setObjectName("ZoomOut1_Button")
        self.horizontalLayout_4.addWidget(self.ZoomOut1_Button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.ZoomIn1_Button = QtWidgets.QPushButton(self.frame_4, clicked = lambda: self.Graph_1.ZoomIn())
        self.ZoomIn1_Button.setMinimumSize(QtCore.QSize(71, 31))
        self.ZoomIn1_Button.setStyleSheet("background-color:#3366ff;")
        self.ZoomIn1_Button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZoomIn1_Button.setIcon(icon4)
        self.ZoomIn1_Button.setObjectName("ZoomIn1_Button")
        self.horizontalLayout_4.addWidget(self.ZoomIn1_Button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.Link_Unlink_Button = QtWidgets.QPushButton(self.frame_4, clicked = lambda: self.Graph_1.Link_Unlink())
        self.Link_Unlink_Button.setStyleSheet("background-color:#3366ff;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/link1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Link_Unlink_Button.setIcon(icon5)
        self.Link_Unlink_Button.setObjectName("Link_Unlink_Button")
        self.verticalLayout_2.addWidget(self.Link_Unlink_Button)
        self.horizontalLayout_2.addWidget(self.frame_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(231, 231))
        self.frame_5.setMaximumSize(QtCore.QSize(1261, 401))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Vert_ScrollBar_Top = QtWidgets.QScrollBar(self.frame_5)
        self.Vert_ScrollBar_Top.setEnabled(False)
        self.Vert_ScrollBar_Top.setProperty("value", 50)
        self.Vert_ScrollBar_Top.setOrientation(QtCore.Qt.Vertical)
        self.Vert_ScrollBar_Top.setObjectName("Vert_ScrollBar_Top")
        self.Vert_ScrollBar_Top.valueChanged.connect(self.Graph_1.VertScroll_Signal)
        self.horizontalLayout_15.addWidget(self.Vert_ScrollBar_Top)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.GraphWidget_Top = PlotWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GraphWidget_Top.sizePolicy().hasHeightForWidth())
        self.GraphWidget_Top.setSizePolicy(sizePolicy)
        self.GraphWidget_Top.setMinimumSize(QtCore.QSize(501, 231))
        self.GraphWidget_Top.setObjectName("GraphWidget_Top")
        self.verticalLayout_7.addWidget(self.GraphWidget_Top)
        self.Horiz_ScrollBar_Top = QtWidgets.QScrollBar(self.frame_5)
        self.Horiz_ScrollBar_Top.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Horiz_ScrollBar_Top.sizePolicy().hasHeightForWidth())
        self.Horiz_ScrollBar_Top.setSizePolicy(sizePolicy)
        self.Horiz_ScrollBar_Top.setOrientation(QtCore.Qt.Horizontal)
        self.Horiz_ScrollBar_Top.setObjectName("Horiz_ScrollBar_Top")
        self.Horiz_ScrollBar_Top.valueChanged.connect(self.Graph_1.Scroll_Signal)
        self.verticalLayout_7.addWidget(self.Horiz_ScrollBar_Top)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(301, 371))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Graph1_Label = QtWidgets.QLabel(self.frame_6)
        self.Graph1_Label.setObjectName("Graph1_Label")
        self.verticalLayout_4.addWidget(self.Graph1_Label, 0, QtCore.Qt.AlignHCenter)
        self.Channels_Top_ComboBox = QtWidgets.QComboBox(self.frame_6)
        self.Channels_Top_ComboBox.setMinimumSize(QtCore.QSize(0, 31))
        self.Channels_Top_ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Channels_Top_ComboBox.setStyleSheet("background-color:#3366ff;")
        self.Channels_Top_ComboBox.setObjectName("Channels_Top_ComboBox")
        self.Channels_Top_ComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.Channels_Top_ComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Edit1_Label_Button = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.Graph_1.Add_Legend())
        self.Edit1_Label_Button.setEnabled(False)
        self.Edit1_Label_Button.setMinimumSize(QtCore.QSize(101, 31))
        self.Edit1_Label_Button.setToolTip("")
        self.Edit1_Label_Button.setStyleSheet("background-color:#3366ff;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Assets/draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit1_Label_Button.setIcon(icon6)
        self.Edit1_Label_Button.setObjectName("Edit1_Label_Button")
        self.horizontalLayout_7.addWidget(self.Edit1_Label_Button)
        self.Label_Top_LineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.Label_Top_LineEdit.setEnabled(False)
        self.Label_Top_LineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.Label_Top_LineEdit.setMaximumSize(QtCore.QSize(133, 16777215))
        self.Label_Top_LineEdit.setStyleSheet("border: 1px solid blue\n"";")
        self.Label_Top_LineEdit.setText("")
        self.Label_Top_LineEdit.setObjectName("Label_Top_LineEdit")
        self.horizontalLayout_7.addWidget(self.Label_Top_LineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Color_Top_Button = QtWidgets.QPushButton(self.frame_6, clicked = lambda : self.Graph_1.Change_Color())
        self.Color_Top_Button.setEnabled(False)
        self.Color_Top_Button.setMinimumSize(QtCore.QSize(101, 31))
        self.Color_Top_Button.setStyleSheet("background-color:#3366ff;")
        self.Color_Top_Button.setObjectName("Color_Top_Button")
        self.horizontalLayout_8.addWidget(self.Color_Top_Button)
        self.AddChannel_Top_Button = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.Graph_1.Add_Channel())
        self.AddChannel_Top_Button.setMinimumSize(QtCore.QSize(0, 31))
        self.AddChannel_Top_Button.setStyleSheet("background-color:#3366ff;")
        self.AddChannel_Top_Button.setObjectName("AddChannel_Top_Button")
        self.horizontalLayout_8.addWidget(self.AddChannel_Top_Button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Move_Top_Button = QtWidgets.QPushButton(self.frame_6, clicked = lambda : self.Graph_1.Move_Signal())
        self.Move_Top_Button.setEnabled(False)
        self.Move_Top_Button.setMinimumSize(QtCore.QSize(134, 31))
        self.Move_Top_Button.setStyleSheet("background-color:#3366ff;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Assets/move-to.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Move_Top_Button.setIcon(icon6)
        self.Move_Top_Button.setObjectName("Move_Top_Button")
        self.horizontalLayout_9.addWidget(self.Move_Top_Button)
        self.Hide_Top_Button = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.Graph_1.Toggle_Hide_Unhide())
        self.Hide_Top_Button.setEnabled(False)
        self.Hide_Top_Button.setMinimumSize(QtCore.QSize(0, 31))
        self.Hide_Top_Button.setStyleSheet("background-color:#3366ff;")
        self.Hide_Top_Button.setObjectName("Hide_Top_Button")
        self.horizontalLayout_9.addWidget(self.Hide_Top_Button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.CineSpeed_Top_Label = QtWidgets.QLabel(self.frame_6)
        self.CineSpeed_Top_Label.setObjectName("CineSpeed_Top_Label")
        self.verticalLayout_4.addWidget(self.CineSpeed_Top_Label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.CineSpeed_Top_Slider = QtWidgets.QSlider(self.frame_6)
        self.CineSpeed_Top_Slider.setMinimum(1)
        self.CineSpeed_Top_Slider.setMaximum(10)
        self.CineSpeed_Top_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.CineSpeed_Top_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.CineSpeed_Top_Slider.setTickInterval(1)
        self.CineSpeed_Top_Slider.setObjectName("CineSpeed_Top_Slider")
        self.CineSpeed_Top_Slider.valueChanged.connect(lambda: self.Graph_1.Cine_Speed(self.CineSpeed_Top_Slider.value()))
        self.horizontalLayout_10.addWidget(self.CineSpeed_Top_Slider)
        self.LCD_Top = QtWidgets.QLCDNumber(self.frame_6)
        self.LCD_Top.setProperty("intValue", 1)
        self.LCD_Top.setObjectName("LCD_Top")
        self.horizontalLayout_10.addWidget(self.LCD_Top)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 251))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 1800))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.frame_16 = QtWidgets.QFrame(self.frame_2)
        self.frame_16.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.Load2_Button = QtWidgets.QPushButton(self.frame_16,clicked=lambda: self.Graph_2.Browse_Signals())
        self.Load2_Button.setStyleSheet("background-color:#3366ff;")
        self.Load2_Button.setIcon(icon)
        self.Load2_Button.setObjectName("Load2_Button")
        self.verticalLayout_3.addWidget(self.Load2_Button)
        self.Play2_Button = QtWidgets.QPushButton(self.frame_16, clicked = lambda : self.Graph_2.Toggle_Play_Pause())
        self.Play2_Button.setEnabled(False)
        self.Play2_Button.setStyleSheet("background-color:#3366ff;")
        self.Play2_Button.setIcon(icon1)
        self.Play2_Button.setObjectName("Play2_Button")
        self.verticalLayout_3.addWidget(self.Play2_Button)
        self.Rewind2_Button = QtWidgets.QPushButton(self.frame_16, clicked = lambda : self.Graph_2.Rewind_Signal())
        self.Rewind2_Button.setEnabled(False)
        self.Rewind2_Button.setStyleSheet("background-color:#3366ff;")
        self.Rewind2_Button.setIcon(icon2)
        self.Rewind2_Button.setObjectName("Rewind2_Button")
        self.verticalLayout_3.addWidget(self.Rewind2_Button)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ZoomOut2_Button = QtWidgets.QPushButton(self.frame_16, clicked = lambda: self.Graph_2.ZoomOut())
        self.ZoomOut2_Button.setMinimumSize(QtCore.QSize(71, 31))
        self.ZoomOut2_Button.setStyleSheet("background-color:#3366ff;")
        self.ZoomOut2_Button.setText("")
        self.ZoomOut2_Button.setIcon(icon3)
        self.ZoomOut2_Button.setObjectName("ZoomOut2_Button")
        self.horizontalLayout_5.addWidget(self.ZoomOut2_Button)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.ZoomIn2_Button = QtWidgets.QPushButton(self.frame_16, clicked = lambda: self.Graph_2.ZoomIn())
        self.ZoomIn2_Button.setMinimumSize(QtCore.QSize(71, 31))
        self.ZoomIn2_Button.setStyleSheet("background-color:#3366ff;")
        self.ZoomIn2_Button.setText("")
        self.ZoomIn2_Button.setIcon(icon4)
        self.ZoomIn2_Button.setObjectName("ZoomIn2_Button")
        self.horizontalLayout_5.addWidget(self.ZoomIn2_Button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem15)
        self.horizontalLayout_6.addWidget(self.frame_16)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.frame_17 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_17.setMaximumSize(QtCore.QSize(1261, 1400))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Vert_ScrollBar_Bottom = QtWidgets.QScrollBar(self.frame_17)
        self.Vert_ScrollBar_Bottom.setEnabled(False)
        self.Vert_ScrollBar_Bottom.setProperty("value", 50)
        self.Vert_ScrollBar_Bottom.setOrientation(QtCore.Qt.Vertical)
        self.Vert_ScrollBar_Bottom.setObjectName("Vert_ScrollBar_Bottom")
        self.Vert_ScrollBar_Bottom.valueChanged.connect(self.Graph_2.VertScroll_Signal)
        self.horizontalLayout_16.addWidget(self.Vert_ScrollBar_Bottom)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.GraphWidget_Bottom = PlotWidget(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphWidget_Bottom.sizePolicy().hasHeightForWidth())
        self.GraphWidget_Bottom.setSizePolicy(sizePolicy)
        self.GraphWidget_Bottom.setMinimumSize(QtCore.QSize(501, 231))
        self.GraphWidget_Bottom.setObjectName("GraphWidget_Bottom")
        self.verticalLayout_6.addWidget(self.GraphWidget_Bottom)
        self.Horiz_ScrollBar_Bottom = QtWidgets.QScrollBar(self.frame_17)
        self.Horiz_ScrollBar_Bottom.setEnabled(False)
        self.Horiz_ScrollBar_Bottom.setOrientation(QtCore.Qt.Horizontal)
        self.Horiz_ScrollBar_Bottom.setObjectName("Horiz_ScrollBar_Bottom")
        self.Horiz_ScrollBar_Bottom.valueChanged.connect(self.Graph_2.Scroll_Signal)
        self.verticalLayout_6.addWidget(self.Horiz_ScrollBar_Bottom)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(301, 571))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Graph2_Label = QtWidgets.QLabel(self.frame_18)
        self.Graph2_Label.setObjectName("Graph2_Label")
        self.verticalLayout_5.addWidget(self.Graph2_Label, 0, QtCore.Qt.AlignHCenter)
        self.Channels_Bottom_ComboBox = QtWidgets.QComboBox(self.frame_18)
        self.Channels_Bottom_ComboBox.setMinimumSize(QtCore.QSize(0, 31))
        self.Channels_Bottom_ComboBox.setStyleSheet("background-color:#3366ff;")
        self.Channels_Bottom_ComboBox.setObjectName("Channels_Bottom_ComboBox")
        self.Channels_Bottom_ComboBox.addItem("")
        self.verticalLayout_5.addWidget(self.Channels_Bottom_ComboBox)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Edit2_Label_Button = QtWidgets.QPushButton(self.frame_18, clicked = lambda: self.Graph_2.Add_Legend())
        self.Edit2_Label_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit2_Label_Button.sizePolicy().hasHeightForWidth())
        self.Edit2_Label_Button.setSizePolicy(sizePolicy)
        self.Edit2_Label_Button.setMinimumSize(QtCore.QSize(134, 31))
        self.Edit2_Label_Button.setMaximumSize(QtCore.QSize(101, 16777215))
        self.Edit2_Label_Button.setStyleSheet("background-color:#3366ff;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Assets/draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit2_Label_Button.setIcon(icon9)
        self.Edit2_Label_Button.setObjectName("Edit2_Label_Button")
        self.horizontalLayout_11.addWidget(self.Edit2_Label_Button)
        self.Label_Bottom_LineEdit = QtWidgets.QLineEdit(self.frame_18)
        self.Label_Bottom_LineEdit.setEnabled(False)
        self.Label_Bottom_LineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.Label_Bottom_LineEdit.setMaximumSize(QtCore.QSize(133, 16777215))
        self.Label_Bottom_LineEdit.setStyleSheet("border: 1px solid blue\n"";")
        self.Label_Bottom_LineEdit.setText("")
        self.Label_Bottom_LineEdit.setObjectName("Label_Bottom_LineEdit")
        self.horizontalLayout_11.addWidget(self.Label_Bottom_LineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Color_Bottom_Button_2 = QtWidgets.QPushButton(self.frame_18, clicked = lambda : self.Graph_2.Change_Color())
        self.Color_Bottom_Button_2.setEnabled(False)
        self.Color_Bottom_Button_2.setMinimumSize(QtCore.QSize(0, 31))
        self.Color_Bottom_Button_2.setStyleSheet("background-color:#3366ff;")
        self.Color_Bottom_Button_2.setObjectName("Color_Bottom_Button_2")
        self.horizontalLayout_12.addWidget(self.Color_Bottom_Button_2)
        self.AddChannel_Bottom_Button = QtWidgets.QPushButton(self.frame_18, clicked = lambda: self.Graph_2.Add_Channel())
        self.AddChannel_Bottom_Button.setMinimumSize(QtCore.QSize(0, 31))
        self.AddChannel_Bottom_Button.setStyleSheet("background-color:#3366ff;")
        self.AddChannel_Bottom_Button.setObjectName("AddChannel_Bottom_Button")
        self.horizontalLayout_12.addWidget(self.AddChannel_Bottom_Button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem19)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Move_Bottom_Button = QtWidgets.QPushButton(self.frame_18, clicked = lambda : self.Graph_2.Move_Signal())
        self.Move_Bottom_Button.setEnabled(False)
        self.Move_Bottom_Button.setMinimumSize(QtCore.QSize(134, 31))
        self.Move_Bottom_Button.setStyleSheet("background-color:#3366ff;")
        self.Move_Bottom_Button.setIcon(icon6)
        self.Move_Bottom_Button.setObjectName("Move_Bottom_Button")
        self.horizontalLayout_13.addWidget(self.Move_Bottom_Button)
        self.Hide_Bottom_Button = QtWidgets.QPushButton(self.frame_18, clicked = lambda : self.Graph_2.Toggle_Hide_Unhide())
        self.Hide_Bottom_Button.setEnabled(False)
        self.Hide_Bottom_Button.setMinimumSize(QtCore.QSize(0, 31))
        self.Hide_Bottom_Button.setStyleSheet("background-color:#3366ff;")
        self.Hide_Bottom_Button.setObjectName("Hide_Bottom_Button")
        self.horizontalLayout_13.addWidget(self.Hide_Bottom_Button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.CineSpeed_Bottom_Label = QtWidgets.QLabel(self.frame_18)
        self.CineSpeed_Bottom_Label.setObjectName("CineSpeed_Bottom_Label")
        self.verticalLayout_5.addWidget(self.CineSpeed_Bottom_Label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.CineSpeed_Bottom_Slider = QtWidgets.QSlider(self.frame_18)
        self.CineSpeed_Bottom_Slider.setMinimum(1)
        self.CineSpeed_Bottom_Slider.setMaximum(10)
        self.CineSpeed_Bottom_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.CineSpeed_Bottom_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.CineSpeed_Bottom_Slider.setTickInterval(1)
        self.CineSpeed_Bottom_Slider.setObjectName("CineSpeed_Bottom_Slider")
        self.CineSpeed_Bottom_Slider.valueChanged.connect(lambda: self.Graph_2.Cine_Speed(self.CineSpeed_Bottom_Slider.value()))
        self.horizontalLayout_14.addWidget(self.CineSpeed_Bottom_Slider)
        self.LCD_Bottom = QtWidgets.QLCDNumber(self.frame_18)
        self.LCD_Bottom.setProperty("intValue", 1)
        self.LCD_Bottom.setObjectName("LCD_Bottom")
        self.horizontalLayout_14.addWidget(self.LCD_Bottom)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem21)
        self.horizontalLayout_6.addWidget(self.frame_18)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 220))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Snapshot_Button = QtWidgets.QPushButton(self.groupBox_2, clicked = lambda: self.Take_Snapshot())
        self.Snapshot_Button.setMinimumSize(QtCore.QSize(221, 0))
        self.Snapshot_Button.setMaximumSize(QtCore.QSize(221, 16777215))
        self.Snapshot_Button.setStyleSheet("background-color:#3366ff;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Assets/snap1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Snapshot_Button.setIcon(icon7)
        self.Snapshot_Button.setObjectName("Snapshot_Button")
        self.horizontalLayout.addWidget(self.Snapshot_Button)
        self.Snapshot_Combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.Snapshot_Combobox.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Snapshot_Combobox.setFont(font)
        self.Snapshot_Combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Snapshot_Combobox.setStyleSheet("background-color:#3366ff;")
        self.Snapshot_Combobox.setObjectName("Snapshot_Combobox")
        self.Snapshot_Combobox.addItem("")
        self.Snapshot_Combobox.addItem("")
        self.horizontalLayout.addWidget(self.Snapshot_Combobox)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.Export_Button = QtWidgets.QPushButton(self.groupBox_2, clicked = lambda : self.Graph_1.Export_PDF())
        self.Export_Button.setEnabled(False)
        self.Export_Button.setMinimumSize(QtCore.QSize(221, 0))
        self.Export_Button.setMaximumSize(QtCore.QSize(221, 16777215))
        self.Export_Button.setStyleSheet("background-color:#3366ff;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Assets/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export_Button.setIcon(icon8)
        self.Export_Button.setObjectName("Export_Button")
        self.horizontalLayout.addWidget(self.Export_Button)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.Title = QtWidgets.QTextBrowser(self.centralwidget)
        self.Title.setMinimumSize(QtCore.QSize(200, 51))
        self.Title.setMaximumSize(QtCore.QSize(341, 51))
        self.Title.setStyleSheet("border:none;")
        self.Title.setObjectName("Title")
        self.gridLayout.addWidget(self.Title, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1689, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMohamed = QtWidgets.QAction(MainWindow)
        self.actionMohamed.setObjectName("actionMohamed")
        self.actionAhmed_Taha = QtWidgets.QAction(MainWindow)
        self.actionAhmed_Taha.setObjectName("actionAhmed_Taha")
        self.actionOmar_Khaled = QtWidgets.QAction(MainWindow)
        self.actionOmar_Khaled.setObjectName("actionOmar_Khaled")
        self.actionYoussef_Hassanein = QtWidgets.QAction(MainWindow)
        self.actionYoussef_Hassanein.setObjectName("actionYoussef_Hassanein")
        self.menuAbout.addAction(self.actionMohamed)
        self.menuAbout.addAction(self.actionAhmed_Taha)
        self.menuAbout.addAction(self.actionOmar_Khaled)
        self.menuAbout.addAction(self.actionYoussef_Hassanein)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.Graph_1.Graph_Window = self.GraphWidget_Top
        self.Graph_2.Graph_Window = self.GraphWidget_Bottom
        self.Graph_1.textbox = self.Label_Top_LineEdit
        self.Graph_2.textbox = self.Label_Bottom_LineEdit
        self.Label_Top_LineEdit.returnPressed.connect(self.Graph_1.Add_Legend)
        self.Label_Bottom_LineEdit.returnPressed.connect(self.Graph_2.Add_Legend)

        self.retranslateUi(MainWindow)
        self.CineSpeed_Top_Slider.valueChanged['int'].connect(self.LCD_Top.display) # type: ignore
        self.CineSpeed_Bottom_Slider.valueChanged['int'].connect(self.LCD_Bottom.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signal Viewer"))
        self.Load1_Button.setText(_translate("MainWindow", "  Load Signal"))
        self.Play1_Button.setText(_translate("MainWindow", "   Pause         "))
        self.Rewind1_Button.setText(_translate("MainWindow", "  Rewind     "))
        self.Link_Unlink_Button.setText(_translate("MainWindow", "    Link Graphs     "))
        self.Graph1_Label.setText(_translate("MainWindow", "Graph 1"))
        self.Channels_Top_ComboBox.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.Edit1_Label_Button.setText(_translate("MainWindow", "  Edit Label"))
        self.Color_Top_Button.setText(_translate("MainWindow", "Select Color"))
        self.AddChannel_Top_Button.setText(_translate("MainWindow", "Add Channel"))
        self.Move_Top_Button.setText(_translate("MainWindow", "  Move"))
        self.Hide_Top_Button.setText(_translate("MainWindow", "Hide / Unhide"))
        self.CineSpeed_Top_Label.setText(_translate("MainWindow", "Cine Speed"))
        self.Load2_Button.setText(_translate("MainWindow", "  Load Signal"))
        self.Play2_Button.setText(_translate("MainWindow", "   Pause         "))
        self.Rewind2_Button.setText(_translate("MainWindow", "  Rewind     "))
        self.Graph2_Label.setText(_translate("MainWindow", "Graph 2"))
        self.Channels_Bottom_ComboBox.setItemText(0, _translate("MainWindow", "Channel 1"))
        self.Edit2_Label_Button.setText(_translate("MainWindow", "  Edit Label"))
        self.Color_Bottom_Button_2.setText(_translate("MainWindow", "Select Color"))
        self.AddChannel_Bottom_Button.setText(_translate("MainWindow", "Add Channel"))
        self.Move_Bottom_Button.setText(_translate("MainWindow", "  Move"))
        self.Hide_Bottom_Button.setText(_translate("MainWindow", "Hide / Unhide"))
        self.CineSpeed_Bottom_Label.setText(_translate("MainWindow", "Cine Speed"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Controls"))
        self.Snapshot_Button.setText(_translate("MainWindow", "   Snapshot"))
        self.Snapshot_Combobox.setItemText(0, _translate("MainWindow", "Graph 1"))
        self.Snapshot_Combobox.setItemText(1, _translate("MainWindow", "Graph 2"))
        self.Export_Button.setText(_translate("MainWindow", "  Export"))
        self.Title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Live Signal Viewer</span></p></body></html>"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionMohamed.setText(_translate("MainWindow", "Mohamed Hazem"))
        self.actionAhmed_Taha.setText(_translate("MainWindow", "Ahmed Taha"))
        self.actionOmar_Khaled.setText(_translate("MainWindow", "Omar Khaled"))
        self.actionYoussef_Hassanein.setText(_translate("MainWindow", "Youssef Hassanein"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())